swagger: '2.0'
info:
  description: "LeApp daemon API"
  version: "1.0"
  title: "LeApp daemon API"
basePath: "/v1"

consumes:
- "application/json"
produces:
- "application/json"

paths:
  /destroy-container:
    post:
      summary: "Delete the container on target"
      parameters:
       - name: "body"
         in: "body"
         required: true
         schema:
           $ref: '#/definitions/DestroyContainerInput'

      responses:
        200:
          description: "Success response"
          schema:
            $ref: '#/definitions/Result'

  /port-inspect:
    post:
      summary: "Inspect ports on target"
      parameters:
       - name: "body"
         in: "body"
         required: true
         schema:
           $ref: '#/definitions/PortInspectInput'

      responses:
        200:
          description: "Success response"
          schema:
            $ref: '#/definitions/Result'

  /port-map:
    post:
      summary: "Map ports given by use or detected on source to ports available on target"
      parameters:
       - name: "body"
         in: "body"
         required: true
         schema:
           $ref: '#/definitions/PortMapInput'

      responses:
        200:
          description: "Success response"
          schema:
            $ref: '#/definitions/Result'


definitions:
  ## Base definitions:
  TargetHostBase:
    type: "object"
    description: "Base schema for target_host field"
    properties:
      target_host:
        type: "string"
        default: "localhost"

  SourceHostBase:
    type: "object"
    description: "Base schema for source_host field"
    required:
      - "source_host"
    properties:
      source_host:
        type: "string"

  PortMapItemBase:
    type: "object"
    description: "Port map item"
    required:
      - "protocol"
      - "exposed_port"
      - "port"
    properties:
      protocol:
        type: "string"
      exposed_port:
        type: "integer"
      port:
        type: "integer"

  PortListItemBase:
    type: "object"
    properties: 
      name: 
        type: "string"
        default: ""

  PortListBase:
    type: "object"
    description: ""
    properties:
      tcp:
        # hash of PortListItemBase 
        description: "A map of ports"
        $ref: "#/definitions/PortListItemBase"
      udp: 
        description: "A map of ports"
        $ref: "#/definitions/PortListItemBase"
        # hash of PortListItemBase 

  ##
  DestroyContainerInput:
    type: "object"
    description: "Destroy/Delete container request"
    required:
      - "container_name"
    properties:
      container_name:
        type: "string"
      target_user:
        type: "string"
        default: "root"
    allOf:
      - $ref: '#/definitions/TargetHostBase'
    type: "object"

  PortInspectInput:
    type: "object"
    description: "Inspect ports request"
    allOf:
      - $ref: '#/definitions/TargetHostBase'
    properties:
      scan_options:
        type: "object"
        properties:
          port_range:
            type: "string"
            default: ""
          shallow_scan:
            type: "boolean"
            default: False

  PortMapInput:
    type: "object"
    description: "Inspect ports request"
    allOf:
      - $ref: '#/definitions/TargetHostBase'
      - $ref: '#/definitions/SourceHostBase'
    properties:
      tcp_ports:
        type: "array"
        items:
          - $ref: '#/definitions/PortMapItemBase'
        default: []
      excluded_tcp_ports:
        type: "array"
        items:
          type: "integer"
        default: []
      default_port_map:
        type: "boolean"
        default: True

  Result:
    description: "Default API response"
    type: "object"
    required:
      - "err_code"
      - "output"
      - "err_message"
    properties:
      err_code:
        type: "integer"
        default: 0
      output:
        type: object
      err_message:
        type: "string"
        default: ""
